### ISSUE TITLE
one click installer

### ISSUE THREAD

**Issue by scavru** [janvarev/kobold_api_multilang_proxy#3]
Привет, можно ли добавить в онклик инсталлер установку LibreTranslate. я руками так и не осилил установку в windows. Если нет то не страшно, обойдемся. Заранее спасибо.

**Comment by janvarev** [comment]
К сожалению да, она там непростая, мне тоже пришлось разбираться.
Поэтому не хочу её сюда добавлять, чтобы на пустом месте не фейлилось. Ну, или может добавлю потом - но отдельным файлом.

**Comment by scavru** [comment]
Было бы здорово, а каким уж способом это не важно, удачи вам в ваших проектах.
